on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: CI

jobs:
  env:
    DB_DATABASE: test_db
    DB_USER: root
    DB_PASSWORD: root    
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}        
 
    - name: Install composer dependencies
      run: |
        composer install -no-interaction --no-suggest --ignore-platform-reqs
 
    - name: Prepare Laravel Application
      run: |
        php artisan key:generate
        
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache           
    - name: Cache Clear
      run: php artisan cache:clear       
    - name: Route Clear
      run: php artisan route:clear      
    - name: Clear Config
      run: php artisan config:clear
    - name: View Clear
      run: php artisan view:clear       
    - name: Run Migration
      run: php artisan migrate          
