on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4
 
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      run: |
        composer install --no-scripts
 
    - name: Prepare Laravel Application
      run: |
        php artisan key:generate
        
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache           
    - name: Cache Clear
      run: php artisan cache:clear       
    - name: Route Clear
      run: php artisan route:clear      
    - name: Clear Config
      run: php artisan config:clear
    - name: View Clear
      run: php artisan view:clear       
    - name: Run Migration
      run: php artisan migrate          
